[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "bevy-bird-ios"
publish = false
version = "0.1.0"

[lib]
crate-type = ["staticlib"]
name = "bevy_bird_ios"

[dependencies]
bevy = {git = "https://github.com/bevyengine/bevy"}
bevy_bird_lib = {path = "../game"}
